const categoryJson = {
  title: "available categories",
  result: {
    Business: "business",
    Entertainment: "entertainment",
    General: "general",
    Health: "health",
    Science: "science",
    Sports: "sports",
    Technology: "technology",
  },
};

const countryJson = {
  title: "available countries",
  result: {
    Argentina: "ar",
    Austria: "at",
    Australia: "au",
    Belgium: "be",
    Bulgaria: "bg",
    Brazil: "br",
    Canada: "ca",
    Switzerland: "ch",
    China: "cn",
    Colombia: "co",
    Cuba: "cu",
    "Czech Republic": "cz",
    Germany: "de",
    Egypt: "eg",
    France: "fr",
    Greece: "gr",
    "Hong Kong": "hk",
    Hungary: "hu",
    Indonesia: "id",
    Ireland: "ie",
    Israel: "il",
    India: "in",
    Italy: "it",
    Japan: "jp",
    "South Korea": "kr",
    Lithuania: "lt",
    Latvia: "lv",
    Morocco: "ma",
    Mexico: "mx",
    Malaysia: "my",
    Nigeria: "ng",
    Netherlands: "nl",
    Norway: "no",
    "New Zealand": "nz",
    Philippines: "ph",
    Poland: "pl",
    Portugal: "pt",
    Romania: "ro",
    Serbia: "rs",
    Russia: "ru",
    "Saudi Arabia": "sa",
    Sweden: "se",
    Singapore: "sg",
    Slovenia: "si",
    Slovakia: "sk",
    "South Africa": "za",
    Thailand: "th",
    Turkey: "tr",
    Taiwan: "tw",
    Ukraine: "ua",
    "United Arab Emirates": "ae",
    "United Kingdom": "gb",
    "United States": "us",
    Venezuela: "ve",
  },
};

const sortByJson = {
  title: "available sort options",
  result: {
    Relevancy: "relevancy",
    Popularity: "popularity",
    PublishedAt: "publishedAt",
  },
};

const searchInJson = {
  title: "available search modes",
  result: {
    Title: "title",
    Description: "description",
    Content: "content",
  },
};

const languageJson = {
  title: "available languages",
  result: {
    Arabic: "ar",
    Germany: "de",
    English: "en",
    Spanish: "es",
    French: "fr",
    Hebrew: "he",
    Italian: "it",
    Dutch: "nl",
    Norwegian: "no",
    Portuguese: "pt",
    Russian: "ru",
    Swedish: "sv",
    Chinese: "zh",
  },
};

export { categoryJson, countryJson, sortByJson, searchInJson, languageJson };
